# 1. 数据库连接：指向你 localhost 的 3306 端口
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# 2. 这里的密码确认是你之前在 Docker 里设置的那个
spring.datasource.password=root_password_123

# 3. 核心保护：使用 update 模式，这样启动时不会删掉你那 100 条数据
spring.jpa.hibernate.ddl-auto=update
# 让 Java 在控制台打印出它执行的 SQL，方便你写论文截图
spring.jpa.show-sql=true